name: HelloWorld
description: This is your personal project
version: v1.1
author: jagmeet@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: jagmeetprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-03-24 08:41:35'
  modifiedAt: '2023-03-24 08:41:35'
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: jagmeet@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-03-24 09:23:01'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: jagmeet@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-03-24 08:41:53'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: jagmeet@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-02-20 09:50:20'
    datasets:
      inputs:
      - datasets/orders
      - datasets/customers
      outputs:
      - datasets/customer_totals
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: jagmeet@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-02-20 09:50:20'
    datasets:
      inputs:
      - datasets/irs-zipcode-data
      - datasets/farmers-markets
      outputs:
      - datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
  pipelines/Demo:
    name: Demo
    description: ''
    author: jagmeet@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-02-28 05:52:28'
    modifiedAt: '2023-02-28 05:52:28'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/report:
    name: report
    description: Final report for the bank
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:19'
    modifiedAt: '2023-02-20 09:50:19'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:19'
        modifiedAt: '2023-02-20 09:50:19'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:19'
    modifiedAt: '2023-02-20 09:50:19'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:19'
        modifiedAt: '2023-02-20 09:50:19'
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:19'
    modifiedAt: '2023-03-24 08:54:59'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:19'
        modifiedAt: '2023-02-20 09:50:19'
  datasets/customers:
    name: customers
    description: All the customers
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:19'
    modifiedAt: '2023-02-20 09:50:19'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:19'
        modifiedAt: '2023-02-20 09:50:19'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:19'
    modifiedAt: '2023-02-20 09:50:19'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:19'
        modifiedAt: '2023-02-20 09:50:19'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:19'
    modifiedAt: '2023-02-20 09:50:19'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:19'
        modifiedAt: '2023-02-20 09:50:19'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-02-20 09:50:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:20'
        modifiedAt: '2023-02-20 09:50:20'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-02-20 09:50:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:20'
        modifiedAt: '2023-02-20 09:50:20'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-02-20 09:50:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:20'
        modifiedAt: '2023-02-20 09:50:20'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: jagmeet@prophecy.io
    createdAt: '2023-02-20 09:50:20'
    modifiedAt: '2023-02-20 09:50:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1619
        datasetType: File
        description: ''
        author: jagmeet@prophecy.io
        createdAt: '2023-02-20 09:50:20'
        modifiedAt: '2023-02-20 09:50:20'
templates: {}
jobs:
  jobs/myJob:
    name: myJob
    description: ''
    fabricUID: 1619
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/customers_orders
    - pipelines/report_top_customers
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-03-24 09:00:52'
    modifiedAt: '2023-03-24 09:01:30'
    author: jagmeet@prophecy.io
functions:
  author: null
  createdAt: '2023-03-24 08:41:35'
  modifiedAt: '2023-03-24 08:41:35'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
